language: julia
os:
  - osx
  - linux
julia:
  - nightly
  - 1.5
notifications:
  email: false

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Simplicial")); include(joinpath("docs", "make.jl"))'
